name: Daily 8AM Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Job Started
        run: echo "Daily 8 AM job started!"

      - name: Display Current Date and Time
        run: date

      - name: Completion Message
        run: echo "Daily 8 AM job completed successfully!"
